{% set name = "utilsforecast" %}
{% set version = "0.2.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/utilsforecast-{{ version }}.tar.gz
  sha256: c36d65d698a88d0fadc93d2d6737c304c3776397c60ae551ee17aa678caf3659

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - packaging
    - pandas >=1.1.1

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - utilsforecast
  commands:
    - pip check

about:
  home: https://github.com/Nixtla/utilsforecast
  summary: Forecasting utilities
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AzulGarza
    - jmoralez
    - cchallu
    - mergenthaler
    - marcopeix
    - elephaint
    - JQGoh
    - nasaul
    - MMenchero
    - goodwanghan
