{% set name = "utilsforecast" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/utilsforecast-{{ version }}.tar.gz
  sha256: 0f19ba507dcc642af190968268ea5407d31b7cfa7e4b9d81f9e9344c96069834

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - packaging
    - pandas >=1.1.1

test:
  imports:
    - utilsforecast
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Nixtla/utilsforecast
  summary: Forecasting utilities
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AzulGarza
    - jmoralez
