{% set name = "utilsforecast" %}
{% set version = "0.2.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/utilsforecast-{{ version }}.tar.gz
  sha256: 73f9dfd836a721a95c349f784bd75e18a4cb7c1469800e325414e22901e9775b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - packaging
    - pandas >=1.1.1

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - utilsforecast
  commands:
    - pip check

about:
  home: https://github.com/Nixtla/utilsforecast
  summary: Forecasting utilities
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AzulGarza
    - jmoralez
    - cchallu
    - mergenthaler
    - marcopeix
    - elephaint
    - JQGoh
    - nasaul
    - MMenchero
    - goodwanghan
