{% set name = "utilsforecast" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/utilsforecast-{{ version }}.tar.gz
  sha256: c89712c2379a93218f4144b56dff3e6ebcd8912f8405b24981c5d36e70fc3ef2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - pandas >=1.1.1

test:
  imports:
    - utilsforecast
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Nixtla/utilsforecast
  summary: Forecasting utilities
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AzulGarza
    - jmoralez
