{% set name = "utilsforecast" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/utilsforecast-{{ version }}.tar.gz
  sha256: 784f4ecc0ac59fcf207652c9de1c9fd16991dd448dd5375826365d90011b88fb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - pandas >=1.1.1

test:
  imports:
    - utilsforecast
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Nixtla/utilsforecast
  summary: Forecasting utilities
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - FedericoGarza
    - jmoralez
